### ISSUE TITLE
v0.4.0.zip release contents?

### ISSUE THREAD

**Issue by TuulaP** [EvidentSolutions/elasticsearch-analysis-voikko#1]
Hi, tried installing the v0.4.0.zip release via:

```
sudo /usr/share/elasticsearch/bin/plugin install https://github.com/EvidentSolutions/elasticsearch-analysis-voikko/archive/v0.4.0.zip
-> Installing from https://github.com/EvidentSolutions/elasticsearch-analysis-voikko/archive/v0.4.0.zip...
Trying https://github.com/EvidentSolutions/elasticsearch-analysis-voikko/archive/v0.4.0.zip ...
Downloading ................................................DONE
```
 

but this happens: 
```
Verifying https://github.com/EvidentSolutions/elasticsearch-analysis-voikko/archive/v0.4.0.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

```
(elasticsearch version is 2.2.0 installed via rpm and all pre-requirements have been installed. )
Or can I create the plugin zip someway?  The zip seem to contain all src files.

**Comment by komu** [comment]
Hi,

You can install the old version using instructions in the [0.4.0 version of README](https://github.com/EvidentSolutions/elasticsearch-analysis-voikko/blob/v0.4.0/README.md).

I'll update the latest README to point to the old version as well.
