### ISSUE TITLE
Support for Elastic Search v6.x / v7.x 

### ISSUE THREAD

**Issue by jsalonen** [EvidentSolutions/elasticsearch-analysis-voikko#3]
Hi!

Do you have plans or interest in adding support for Elasticsearch v6.x or v7.x? Would be happy to provide assistance if required.

**Comment by komu** [comment]
We don't have any immediate plans to add support since we don't have a need for it ourselves.

But I suppose that updating would be relatively easy and mostly consist of testing that everything indeed works with the new version. I'd be happy to merge a PR supporting later versions of ES if it has been given some testing.

**Comment by ivarekman** [comment]
> 
> 
> Hi!
> 
> Do you have plans or interest in adding support for Elasticsearch v6.x or v7.x? Would be happy to provide assistance if required.

@jsalonen did you get anywhere in regards to getting this working on a more modern Elasticsearch version? I have the same need and it seems it did not fly after a quick test on 7.3.1.

**Comment by jsalonen** [comment]
@ivarekman Short recap on what has been done:

Got notified that @peerkar has been working on a fork.

See the following branch for ES 6.x support: https://github.com/peerkar/elasticsearch-analysis-voikko/tree/gsearch-es-613

I got instructions that you should be able to build this with

`./gradlew build -x compileTestJava -x checkstyleMain -x checkstyleTest -x test -x integTestRunner`

To my understanding this port should work for ES 6, but I haven't tested it myself.

Note that tests have not been refactored so they fail. So for a complete upstream PR I would fix those.

A colleague was also working with a port, but it didn't end up completing. I'm polling for information where it is going, will get back on that later.

Many have attempted, but none complete solutions have been PRed upstream. **Now that we are gaining traction, let's work together and make this PR happen**

**Comment by ivarekman** [comment]
Thanks @jsalonen! We decided to start to work on this in one customer case. Hopefully we'll get it resolved soon. Currently we are running the latest (7.3) ELasticsearch and that is initially where we'd like to use Voikko also. We are also working on getting permission to share the developments publicly. I, or someone else from the team, will hopefully update the status here when we're done.

**Comment by hakuzumon** [comment]
FYI: Our customer also decided to upgrade their elastic instance, so I made a branch for the latest elastic version. Note that it's not final yet, but will probably be included in an "official" release, if it works ok.

**Comment by komu** [comment]
I just released `0.6.0` with @hakuzumon's changes. Required code changes were minimal, but there were some changes in the build system of plugins.

Anyway, it seems to work nicely with ES 7.3.2. Please take it for a spin.
